### ISSUE TITLE
P8702N stopped working

### ISSUE THREAD

**Issue by vahidtakro** [threader/zyxel-p8702n-bcm63xx#1]
Hello, yesterday I decided to upgrade my modem ZyXEL P8702N (Telenor) firmware. I downloaded a .bin file, as a newer version of the modem firmware, I started upgrading the modem through the administrator URL 10.0.0.138, suddenly after a restart, modem is no longer working. when I power on the modem, the power light only blinks, the WPS light is off. What can I do? how can I recover my modem? I'll be thankful if you can help me.

**Comment by threader** [comment]
Hey, sorry, I didn't see this message before now. I had to get a USB to serial and forcefully flash an older .bin , telenor locked these with the latest firmwares.

I did all the research and found all these sources etc after I dug trough old backups when I did that, I can't remember now what was the last firmware that wasn't locked to the telenor WAN. I toyed with the idea of using a telenor sim card and trying to set it up that way before i found my USB to serial cable. Cheers.

**Comment by threader** [comment]
User flashed wrong firmware. I will see if I can document this better in the readme

**Comment by threader** [comment]
> Hello, yesterday I decided to upgrade my modem ZyXEL P8702N (Telenor) firmware. I downloaded a .bin file, as a newer version of the modem firmware, I started upgrading the modem through the administrator URL 10.0.0.138, suddenly after a restart, modem is no longer working. when I power on the modem, the power light only blinks, the WPS light is off. What can I do? how can I recover my modem? I'll be thankful if you can help me.

Err. Now I remember you hold in some button, reset I believe while powering on, until you see something blinking red I believe, set up a static IP to something like 192.168.1.30 and connect to 192 168.1.1  I will need to re read some documentation to give you the exact IP etc.

I recommend you read the links and docs in the repo. 

I believe you are in this mode with the blinking light so it's a matter of setting up the correct IP. Firmwares are in the firmware folder in this repo

**Comment by threader** [comment]
I updated the README.txt a bit, uploaded the latest firmware i could find, I thought i had uploaded this before, but its 100AAJX14D0.bin anyway, and  I think I explained how to force flash correctly in that mode I cant remember the name of, if you have any of the later firmwares laying around please give me a shout, It's entirely possible to revert the management system to the old one i believe, though efforts should be made to compile the mainline Linux kernel and latest OpenWRT for this device.

**Comment by vahidtakro** [comment]
@threader Thank you Michael, you're amazing. That's so kind of you. However since I found your reply yesterday, I am searching how to force flash it, even though I read in the README.txt, about holding the reset button, etc, I wonder if is there any specific application to use? or where to add the 100AAJX14D0.bin file?

**Comment by threader** [comment]
You just use a browser and enter 192.168.1.1 and it should be in the menu there, but with a simplistic fallback of a UI, I might need to re-read some documentation myself, the pictures i remember of the pins for a serial console were horrid as well. I wish i would get better notifications of messages like this, i have the GitHub app on my phone so i didn't expect to miss anything, wups.

**Comment by vahidtakro** [comment]
> You just use a browser and enter 192.168.1.1 and it should be in the menu there, but with a simplistic fallback of a UI

oh that's the problem, as the modem firmware is broken, the modem is not accessible through any IP.

**Comment by threader** [comment]
not even with a static ip set on the machine? if you say set the PC to 192.168.1.30 the modem should be on 192.168.1.1

**Comment by vahidtakro** [comment]
> not even with a static ip set on the machine? if you say set the PC to 192.168.1.30 the modem should be on 192.168.1.1

I'm not sure, I just remember I used this IP to access the modem settings: 10.0.0.138
I'm not a pro user of GitHub, but I receive a mail on each reply; I also use different text apps if that makes it easy for you.

**Comment by threader** [comment]
Ah yes, that's in the Telenor Firmware mode 10.0.0.138 is the IP, the fallback has no DHCP , i found this poorly documented as well, not to mention that telenor snubbed my attempt to get them to send me all the latest firmwares, or sources, or anything... .

**Comment by vahidtakro** [comment]
Tftpd64, I remember I was reading on some websites that this app can help a lot, what do you think? have you ever worked with it?

**Comment by threader** [comment]
No never, wouldn't be of any use to this project either sadly. OpenWRT has everything we want already, I just got busy with other things and tired of trying to maintain old outdated linux kernels with no git history

**Comment by vahidtakro** [comment]
oh means there is no way to recover this modem and bring it back to life? I don't even know what OpenWRT is, just busy around with React JavaScript codes in Github...

**Comment by threader** [comment]
I will see if I can't find the exact documentation when I have time, but the golden rule is if there is light there is life, and you have lights so there is hope.

**Comment by threader** [comment]
I updated the readme a bit and re-read a bit of documentation but this is what you do:

To force flash firmware:
from zyxel-p8702n-bcm63xx/doc/bcm963xx_bootloader_appnote.pdf :
"
1. Press and hold the reset button until the “DSL” LED goes on. It will take about 8 seconds.
2. Configure a PC Ethernet connection with a static IP address on subnet 192.168.1.x.
3. Open a Web browser to IP address 192.168.1.1. The following screen will appear.
"
To flash a non Telenor WAN locked firmwre, you can now select:
'zyxel-p8702n-bcm63xx/firmware/p8702/100AAJX14D0.bin

**Comment by vahidtakro** [comment]
That's the thing, DSL LED never turns on, and the modem is not reachable through any IP address...

**Comment by threader** [comment]
Huuuh, you need to see what the router says via the serial connection, I'll upload some new pictures for serial connection in a bit. As understand it, the firmware flash you went trough might have somewhere failed somehow? I'm starting to wonder if we would need digging up more documentation for this, i can't remember if i did or not infact read how to do this or if it was for a phone, but i'm guessing you might not be too keen on soldering wires or pins to your modem? I'd like to get in touch with others using this, it's still a useful modem/router ( cant decide if i want to call it modem or router or so so sorry ). i believe mainline linux with the latest OpenWRT is within a leangth of breath fresh air. I just briefly read trough the manual now while verifying what i said to you and README.txt, there is a way to boot new kernels uploading the image etc via CFE, i cant remember if this device was u-boot, but i read trough while doing some stuff with the the-c64-mini and found a workaround to boot newer kernels on older uboots. Again, please say if you know of anyone using this modem, i'd like to get in touch on a Telegram group or Signal or so.

**Comment by threader** [comment]
Mkay, https://github.com/threader/zyxel-p8702n-bcm63xx/commit/0c27eedb032246b9ac0a91c3756f44580e3e1843 - good luck
